### ISSUE TITLE
Regarding OTP

### ISSUE THREAD

**Issue by Soumya7391** [firebase/digits-migration-helper-android#2]
I used this code, its working fine for me. But I don't get OTP. It just verifies and gets to next layout. Why is that so?

**Comment by ashwinraghav** [comment]
The design goal of this SDK is to preserve the digits sessions and _transparently_ exchange it for a firebase session. So the behavior you are seeing is intended. Check out our [android migration documentation](https://firebase.google.com/support/guides/digits-android) for more details
